### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by lazarofl** [alisonmonteiro/nth-rocks#7]
@alisonmonteiro Ao invés de usar bower porque não usar apenas o npm para instalar o pacote?

**Comment by alisonmonteiro** [comment]
Oi, @lazarofl 
A ideia é liberar também para a galera que usa o bower. Apesar de utilizar apenas o npm, acho que as pessoas que ainda não o utilizam podem baixar também :+1:

**Comment by lazarofl** [comment]
Do que precisa para registrar no bower?

**Comment by alisonmonteiro** [comment]
É bem simples. Apenas criar o bower.json com as informações já contidas no package.json. (PR são bem-bindos)
Depois, vou [registrar](http://bower.io/docs/creating-packages/#register) o pacote daqui. :)
